# Dependencies
markdown:         redcarpet
highlighter:      pygments
version:          v0.4.2

# Permalinks
permalink:        pretty

# Setup
title:            exVim
tagline:          ''
description:      ''
url:              http://exvim.github.io

author:
  name:           'exVim Organization'
  url:            http://github.com/exvim

github:
  repo:           https://github.com/exvim/main

# Markup language setup
redcarpet:
  extensions:     [
      "no_intra_emphasis", 
      "fenced_code_blocks", 
      "autolink", 
      "strikethrough", 
      "superscript",
      "tables",
      "with_toc_data",
      "footnotes",
  ]

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Navigation
navigation:
- text: Home
  url: /
  layout: index
- text: Downloads
  url: /downloads/
  layout: downloads
- text: Docs
  url: /docs/
  layout: docs
- text: Docs(中文)
  url: /docs-zh/
  layout: docs-zh
- text: GitHub
  url: https://github.com/exvim/main
- text: Changelog
  url: https://github.com/exvim/main/releases
- text: About
  url: /about/
  layout: index

# User Manual
user_manual:
- text: Intro
  url: /intro/
- text: Install
  url: /install/
- text: Getting Start
  url: /getting-start/
- text: Project Window
  url: /project-window/
- text: Global Search
  url: /global-search/
- text: Tags And Symbols
  url: /tags-and-symbols/
- text: View Class Hierarchies
  url: /view-class-hierarchies/
- text: Config .exvim
  url: /config-exvim/
- text: Config .vimrc
  url: /config-vimrc/
- text: Config Color Scheme
  url: /config-colorscheme/
- text: Plugins
  url: /plugins/
- text: Known Issues
  url: /known-issues/

# Developer Manual
dev_manual:
- text: Select Your Plugin
  url: /select-your-plugin/
- text: Build Your Distribution
  url: /build-your-distribution/

# User Manual
user_manual_zh:
- text: 简介
  url: /intro/
- text: 安装
  url: /install/
- text: 开始入门
  url: /getting-start/
- text: 工程窗口
  url: /project-window/
- text: 全局搜索
  url: /global-search/
- text: 标签与符号
  url: /tags-and-symbols/
- text: 类继承图谱
  url: /view-class-hierarchies/
- text: exvim 项目配置
  url: /config-exvim/
- text: vimrc 配置
  url: /config-vimrc/
- text: 颜色主题配置
  url: /config-colorscheme/
- text: 插件
  url: /plugins/
- text: 已知问题
  url: /known-issues/

# Developer Manual
dev_manual_zh:
- text: 选择你的插件
  url: /select-your-plugin/
- text: 创建你的发布版本
  url: /build-your-distribution/
